import { NextRequest, NextResponse } from "next/server";

export async function POST(
  _request: NextRequest,
  { params }: { params: { id: string } }
) {
  const scanId = params.id;

  // TODO: Fetch pre-generated PDF URL from Supabase Storage
  // TODO: Return signed URL (PDF generated by worker, not on-demand)

  return NextResponse.json({
    scan_id: scanId,
    pdf_url: null,
    error: "PDF not yet generated",
  });
}
